service: maggyeo
frameworkVersion: "3"

custom:
  stage: ${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}
  environment:
    stage: ${self:provider.stage}
    TARGET_ENV: ${self:provider.stage}

functions:
  getUser:
    handler: src/controllers.getUser
    events:
      - http:
          path: user/{userId}
          method: get
  patchUser:
    handler: src/controllers.patchUser
    events:
      - http:
          path: user/{userId}
          method: patch

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
