service: maggyeo
frameworkVersion: "3"

custom:
    stage: ${opt:stage, 'dev'}

provider:
    name: aws
    runtime: nodejs14.x
    region: ap-northeast-2
    stage: ${opt:stage, 'dev'}
    environment:
        stage: ${self:provider.stage}
        TARGET_ENV: ${self:provider.stage}

functions:
    getUserInfo:
        handler: src/controllers/index.getUserInfo
        events:
            - http:
                  path: user/{userId}
                  method: get

    getUserList:
        handler: src/controllers/index.getUserList
        events:
            - http:
                  path: user/{userId}/list
                  method: get

    getUserParticipate:
        handler: src/controllers/index.getUserParticipate
        events:
            - http:
                  path: user/{userId}/participate
                  method: get

    getUserReceivedMessage:
        handler: src/controllers/index.getUserReceivedMessage
        events:
            - http:
                  path: user/{userId}/message
                  method: get

    createUser:
        handler: src/controllers/index.createUser
        events:
            - http:
                  path: user
                  method: post

    patchUser:
        handler: src/controllers/index.patchUser
        events:
            - http:
                  path: user/{userId}
                  method: patch

    getPresentList:
        handler: src/controllers/index.getPresentList
        events:
            - http:
                  path: list/{listId}
                  method: get

    getPresentLists:
        handler: src/controllers/index.getPresentLists
        events:
            - http:
                  path: list
                  method: get
    patchPresentList:
        handler: src/controllers/index.patchPresentList
        events:
            - http:
                  path: list/{listId}
                  method: patch
    createPresentList:
        handler: src/controllers/index.createPresentList
        events:
            - http:
                  path: list
                  method: post
    deletePresentList:
        handler: src/controllers/index.deletePresentList
        events:
            - http:
                  path: list/{listId}
                  method: delete
plugins:
    - serverless-plugin-typescript
    - serverless-offline
    - serverless-dotenv-plugin
